// same as VJsjNoDeps but requiring each used component of vuetify to try working well with vuetify-loader

import VJsfNoNeps from './VJsfNoDeps'

import {
  VAlert,
  VAvatar,
  VAutocomplete,
  VBtn,
  VCard,
  VCardActions,
  VCardText,
  VCardTitle,
  VCheckboxBtn,
  VCheckbox,
  VChip,
  VColorPicker,
  VCombobox,
  VContainer,
  VDialog,
  VDivider,
  VExpansionPanels,
  VExpansionPanel,
  VExpansionPanelTitle,
  VExpansionPanelText,
  VCol,
  VFileInput,
  VIcon,
  VInput,
  VRow,
  VList,
  VListGroup,
  VListSubheader,
  VListItem,
  VListItemTitle,
  VListItemSubtitle,
  VListItemAction,
  VListImg,
  VListItemMedia,
  VMenu,
  VRadio,
  VRadioGroup,
  VSelect,
  VSlider,
  VSpacer,
  // VSubheader,
  VSwitch,
  VTabs,
  VTab,
  // VTabItem,
  VTextarea,
  VTextField,
  // VTimePicker,
  VTooltip
} from 'vuetify/lib/components/index.mjs'

import {
  ClickOutside
} from 'vuetify/lib/directives/index.mjs'
import { VDatePicker } from 'vuetify/lib//labs/VDatePicker/VDatePicker.mjs'
import { VStepper } from 'vuetify/lib//labs/VStepper/VStepper.mjs'
import { VStepperWindow } from 'vuetify/lib//labs/VStepper/VStepperWindow.mjs'
import { VStepperHeader } from 'vuetify/lib//labs/VStepper/VStepperHeader.mjs'
import { VStepperItem } from 'vuetify/lib//labs/VStepper/VStepperItem.mjs'
import { VStepperWindowItem } from 'vuetify/lib//labs/VStepper/VStepperWindowItem.mjs'
export default {
  name: 'VJsf',
  directives: { ClickOutside },
  components: {
    VAlert,
    VAvatar,
    VAutocomplete,
    VBtn,
    VCard,
    VCardActions,
    VCardText,
    VCardTitle,
    VCheckboxBtn,
    VCheckbox,
    VChip,
    VColorPicker,
    VCombobox,
    VContainer,
    VDatePicker,
    VDialog,
    VDivider,
    VExpansionPanels,
    VExpansionPanel,
    VExpansionPanelTitle,
    VExpansionPanelText,
    VCol,
    VFileInput,
    VIcon,
    VInput,
    VRow,
    VList,
    VListGroup,
    VListSubheader,
    VListItem,
    VListItemTitle,
    VListItemSubtitle,
    VListItemAction,
    VListImg,
    VListItemMedia,
    VMenu,
    VRadio,
    VRadioGroup,
    VSelect,
    VSlider,
    VSpacer,
    VStepper,
    VStepperWindow,
    VStepperHeader,
    VStepperItem,
    VStepperWindowItem,
    // VSubheader,
    VSwitch,
    VTabs,
    VTab,
    // VTabItem,
    VTextarea,
    VTextField,
    // VTimePicker,
    VTooltip
  },
  mixins: [VJsfNoNeps]
}
